"""
Dynamic Gate Controller for hardware-level K/V compute bypass.

Reads gating profiles generated by the AutoProfiler and enforces
hardware gating decisions at inference time, tracking compute savings.
"""

import json
import logging
from typing import Dict, Optional, Set, Tuple

import torch

from .policies import GatingPolicy

logger = logging.getLogger(__name__)


class DynamicGateController:
    """Controls dynamic inference gating for Spiking Transformers.

    Based on profiling policies (e.g., LATE_WAKEUP, DYNAMIC_ONLINE_PRUNING),
    this controller decides per-head, per-timestep whether to physically
    bypass Key and Value matrix multiplications.

    Args:
        profile_path: Path to a JSON gating profile generated by ``AutoProfiler``.
        online_sparsity_threshold: Q-sparsity threshold for ``DYNAMIC_ONLINE_PRUNING``.
            Heads with sparsity above this value are killed at runtime.
    """

    def __init__(
        self,
        profile_path: Optional[str] = None,
        online_sparsity_threshold: float = 0.95,
    ) -> None:
        self.policies: Dict = {}
        self.bypassed_kv_computations: int = 0
        self.total_kv_computations: int = 0
        self.dynamically_pruned_heads: Set[Tuple[int, int]] = set()
        self.online_sparsity_threshold = online_sparsity_threshold

        # Ablation study overrides
        self.override_policy: Optional[str] = None
        self.override_mode: Optional[str] = None       # "MASK_ONE" or "ISOLATE_ONE"
        self.override_target: Optional[Tuple[int, int]] = None

        if profile_path is not None:
            self.load_profile(profile_path)

    def load_profile(self, profile_path: str) -> None:
        """Loads a gating profile from a JSON file."""
        with open(profile_path, "r") as f:
            self.policies = json.load(f)
        logger.info("Loaded gating profile from %s", profile_path)

    def reset_state(self) -> None:
        """Clears memory of dynamically pruned heads for a new forward pass."""
        self.dynamically_pruned_heads.clear()

    def reset_compute_counters(self) -> None:
        """Resets the bypass/total computation counters."""
        self.bypassed_kv_computations = 0
        self.total_kv_computations = 0

    def get_head_policy(self, block_idx: int, head_idx: int) -> str:
        """Returns the hardware gating policy string for a specific head.

        Override modes (for ablation studies) take precedence over
        the loaded JSON profile.
        """
        if self.override_mode == "MASK_ONE":
            if self.override_target == (block_idx, head_idx):
                return GatingPolicy.STATICALLY_PRUNE_OR_EARLY_EXIT_T1.value
            return GatingPolicy.ACTIVE_NO_GATE.value

        if self.override_mode == "ISOLATE_ONE":
            if self.override_target == (block_idx, head_idx):
                return GatingPolicy.ACTIVE_NO_GATE.value
            return GatingPolicy.STATICALLY_PRUNE_OR_EARLY_EXIT_T1.value

        if self.override_policy is not None:
            return self.override_policy

        try:
            return self.policies[f"block_{block_idx}"][f"head_{head_idx}"]["HARDWARE_GATING_POLICY"]
        except KeyError:
            return GatingPolicy.ACTIVE_NO_GATE.value

    def should_compute_kv(
        self,
        block_idx: int,
        head_idx: int,
        timestep: int,
        q_spikes: torch.Tensor,
    ) -> bool:
        """Determines whether K/V computations should execute for this head.

        Args:
            block_idx: Current transformer block index.
            head_idx: Current attention head index.
            timestep: Current simulation timestep (0-indexed).
            q_spikes: Binary spike output from the Query LIF node.

        Returns:
            ``True`` if K and V should be computed, ``False`` to bypass.
        """
        self.total_kv_computations += 1
        policy = self.get_head_policy(block_idx, head_idx)

        should_compute = True

        # 1. Statically Pruned Heads: never compute K or V
        if policy == GatingPolicy.STATICALLY_PRUNE_OR_EARLY_EXIT_T1:
            should_compute = False

        # 2. Redundant Heads: statically shut off
        elif policy == GatingPolicy.STATICALLY_GATED_BY_REDUNDANCY:
            should_compute = False

        # 3. Late Wakeup Gate: Wait for Q to spike before computing K and V
        elif policy == GatingPolicy.LATE_WAKEUP_GATE:
            if timestep == 0:
                batch_spiked = q_spikes.max().item() > 0
                should_compute = batch_spiked

        # 4. Dynamic Online Pruning: Real-time inference proxy
        elif policy == GatingPolicy.DYNAMIC_ONLINE_PRUNING:
            if (block_idx, head_idx) in self.dynamically_pruned_heads:
                should_compute = False
            else:
                sparsity = 1.0 - q_spikes.mean().item()
                if sparsity > self.online_sparsity_threshold:
                    self.dynamically_pruned_heads.add((block_idx, head_idx))
                    should_compute = False

        if not should_compute:
            self.bypassed_kv_computations += 1

        return should_compute
